### ISSUE TITLE
is datajoint data cached locally?

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/IBL-pipeline#12]
There is no clear path set for caching - is datajoint fetching all data each time a fetch command is run? this may become slow with many repeated fetches of the same data

**Comment by dimitri-yatsenko** [comment]
The data that are configured to be stored in S3 can be fetched locally.  We have just improved how external storage is configured and will provide instructions shortly: https://github.com/datajoint/datajoint-python/pull/532

The Vathes team will help configure the pipeline so that fetches will be cached for optimal performance and cost.

**Comment by austin-hilberg** [comment]
@dimitri-yatsenko 's comment refers to caching and fetching data stored externally (in S3, as opposed to directly within the RDS). This consideration is related to but separate from the issue @anne-urai has brought up, which is local caching on a client system. I will follow up shortly.

**Comment by austin-hilberg** [comment]
Yes, DJ fetches all data from the server to the local system every time `fetch` is called. However, this doesn't have to cause a slowdown with repeated use of data. When multiple fetch calls are retrieving the same data, the solution is to save the output of the first fetch as a local variable and to refer to the local variable for each subsequent use. [This is particularly relevant when iterating over many entities.](https://docs.datajoint.io/python/queries/04-Iteration.html) Essentially, DJ allows the user to determine the correct trade-off between transfers over the network and local memory use.

You could also run into repeated fetch calls in the following pattern: bulk data are fetched (e.g. for all mice), a subset of those data are used (e.g. a single mouse), the bulk data are fetched again (e.g. all mice again), and a different subset of the data are used (e.g. a second single mouse). I'm not sure that this case applies to your code, but in this situation the solution is to directly fetch the particular data subsets using more precise queries. If you find yourself fetching data and then only working with some of the fetched data, then the query for the fetch call might be too general.

@anne-urai Let me know if this does not fully address your question/concern.
