### ISSUE TITLE
DJ notebook that enables one to recreate the session page

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/IBL-pipeline#45]
![image](https://user-images.githubusercontent.com/43007596/62775196-e6b91880-ba9e-11e9-94ad-3a3222eb00fa.png)

Feature request : It would be great to have a DJ notebook that enables one to recreate the session page given a subject and date.

For example, I would like to check what happened on July 18th for IBL_T3 of angelaki lab (see image) - but the data is no longer visible on DJ website as not one of the last 3 sessions.

**Comment by shenshan** [comment]
The session page contains data of all sessions. Would that satisfy your needs?

**Comment by GaelleChapuis** [comment]
Yes this would satisfy my needs, thank you! You can close the issue.

**Comment by shenshan** [comment]
Cool.
