### ISSUE TITLE
Changes to load_object

### ISSUE THREAD

**Issue by k1o0** [int-brain-lab/IBL-pipeline#55]
https://github.com/int-brain-lab/IBL-pipeline/blob/ef31b2da8fbae1d25e776accbb002ed07f95a1b2/scripts/updates/update_rt.py#L34

FYI on develop `alf.io.load_object` and `ONE().load_object` have changed a little.  Now the namespace must be a separate kwarg (if you don't provide the arg then the namespace is ignored altogether).  The above line would now be `alf.io.load_object(..., 'trials', namespace='ibl')` or just `alf.io.load_object(..., 'trials')`.

**Comment by rossant** [comment]
to be closed as part of the ONE v2 discussion
