### ISSUE TITLE
automatically find .one_params

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/IBL-pipeline#6]
the `.one_params` will be installed in the same location for everyone (https://ianlunn.co.uk/articles/quickly-showhide-hidden-files-mac-os-x-mavericks/) - can Docker use that file instead of having to copy it to a new location within `IBL-pipeline/root`?

**Comment by oliche** [comment]
Without a dependency:
```
from pathlib import Path
Path.home()
```

Recommended way:
```
from ibllib.io import params
par = params.read('one_params')
```

Those are the small things that are good to share with the library so that you'll get updates (for example when we add Globus support to ONE).

**Comment by GaelleChapuis** [comment]
Could you please indicate whether this README step is still necessary: 

6. Copy your `.one_params` file into `IBL-pipeline/root` to not be prompted for Alyx login (see https://ibllib.readthedocs.io/en/latest/02a_installation_python.html).

**Comment by GaelleChapuis** [comment]
Also: do we need to clone ibllib prior to IBL-pipeline in order to obtain the .one_params ?

**Comment by shenshan** [comment]
In the next pull request, we will change the mapping of the `.one_params` file in the `docker-compose-template.yml`,  as `~/.one_params: /root/.one_params`. Users already had their `.one_params` set up just need to `cp` the `docker-compose-template.yml` as `docker-compose.yml`.
