### ISSUE TITLE
streamline folder names

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/IBL-pipeline#7]
Right now there is `IBL-pipeline`, the top-level repo name, `ibl_pipeline`, the subfolder where analyses are stored, and `ibl-pipeline`, the folder where this is mapped after starting. This is quite confusing, could the names be made more informative?

**Comment by shenshan** [comment]
It is a good point. We would change the mapped folder to `IBL-pipeline` to match the repo name in the next PR. ibl_pipeline is the package name that is installed. The convention is to name with `_`.

**Comment by shenshan** [comment]
Fixed by changing the mapped folder to `IBL-pipeline`
