### ISSUE TITLE
map docker to ibl_pipeline rather than notebooks folder

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/IBL-pipeline#8]
Most users will want to run python code that is in a script, not a notebook. Given that the location of the scripts is changing, could there be a stable top-level `scripts` folder where the user is dropped after running `ibl_docker_setup.sh`?

**Comment by shenshan** [comment]
Yes, we figured out a method to achieve this. In your `ibl_docker_setup.sh`, replace the last line with the following:
```
docker exec -it ibl-pipeline_datajoint_1 sh -c 'cd /src/ibl-pipeline/scripts; exec /bin/bash'
```

**Comment by anne-urai** [comment]
great! could you change that in the upstream so that future users automatically get that version?

**Comment by shenshan** [comment]
Yes I changed them. It depends on which folder they want to go to. So I leave it in a commenting line.

**Comment by anne-urai** [comment]
Can you be more specific? I just pulled from upstream but I'm still landing in the notebooks folder when running `ibl_docker_setup.sh`
