### ISSUE TITLE
local volume mapping in docker-compose.yml lost when pulling from upstream

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/IBL-pipeline#9]
Once the user has created a mapping between a local folder on disk and a Docker alias, this is overwritten when pulling new code from upstream. Can there be a local `FIGURE_DIR` (similar to `CACHE_DIR` in `.one_params` that doesn't change?

**Comment by shenshan** [comment]
In the newest version of code. We created a `docker-compose-template.yml`, and removed the `docker-compose.yml` from the repository by adding that in the `.gitignore`. We did the same thing to the `docker-compose-local.yml`. Locally, if you would do the following, this issue would be solved.
1. `git rm --cache docker-compose.yml`
2. `git rm --cache docker-compose-local.yml`
3. `git commit -m "Remove the personalized docker-compose files."`
3. pull from upstream

**Comment by shenshan** [comment]
@anne-urai would you confirm the approach listed worked for you? If so, I would close the issue.

**Comment by shenshan** [comment]
@GaelleChapuis would you mind doing a similar thing?

**Comment by anne-urai** [comment]
done, works for me

**Comment by GaelleChapuis** [comment]
@shenshan texted you on Slack as I have conflict issues.
